name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify --themesDir ../..  
        
      - name: SSH setup
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" >> ~/.ssh/id_rsa
          echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          chmod -R 700 ~/.ssh        
      - name: Rsync deployment
        run: |
                rsync -avzv -e  ssh --delete public/ blog@www.variplait.de:/var/www/blog/variplait.de
      #- name: Deploy
       # uses: peaceiris/actions-gh-pages@v3
       # if: github.ref == 'refs/heads/main'
       # with:
       #   github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_dir: ./public
